name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CONFIGURATION: Release
  DOTNET: 6.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore